Feauture/rest api
EvgeniyAbramovich/Qase_EvgeniyAbramovich_QA22 pull request #3
Opened 2023-02-14 20:56 UTC by EvgeniyAbramovich

2023-02-16 12:38 UTC, voropa requested changes

2023-02-16 12:38 UTC, voropa commented on src/test/java/APITests/APITests.java
> +    public void verifyGetDefectsRequestReturnsBodyData () {
Раз уж это дипломный проект, то сделайте api тесты красиво, чтобы они были частью дипломной работы. Примените паттерн adapter, который я показывал в прошлую пятницу и сбрасывал вм даже пример репозитория, где есть код с реализацией

2023-03-02 13:46 UTC, voropa requested changes

2023-03-02 13:46 UTC, voropa commented on src/test/java/adapters/BaseAdapter.java
> +
Сделайте глобальнцю конфигурацию RestAssured, например, в конструкторе этого класса, чтобы не дублировать один и те же header'ы в каждом запросе
        RestAssured.baseURI = BASE_URL;
        RestAssured.requestSpecification = given()
                .header("Token", ACCESS_TOKEN)
                .header(HTTP.CONTENT_TYPE, ContentType.JSON);

2023-03-02 13:46 UTC, voropa commented on src/test/java/adapters/ProjectAdapter.java
> +    public String deleteProjectByCode(){
А этот метод чего не реализован?

2023-03-02 13:46 UTC, voropa commented on src/test/java/apitests/SimpleAPITests.java
> +    private static final String TOKEN = "e25efa9b75dc801c68cbf3e4efb14f48ab418746533f296cfee28e4a47f1aed1";
Я так понимаю, что это был тестовый класс с наработками в рамках домашки и к дипломнойо работе он отношения не имеет, удали его в таком случае

2023-03-02 13:46 UTC, voropa commented on src/test/java/modals/NewConfigurationsModal.java
> +    public void fillformConfigurations(Configurations configurations) {
Раз уж в используете Chain Of Invocattions pattern, то он должен быть применен везде, и у вас не должно быть void методов. Все void методы должны возвращать this - ссылку на текущий обьект-страницу

2023-03-02 13:46 UTC, voropa commented on src/test/java/modals/NewDefectModal.java
> +    public void fillformDefects(Defects defects) {
То же самое тут с void

2023-03-02 13:46 UTC, voropa commented on src/test/java/pages/BasePage.java
> +        protected static WebDriver driver;
Вм по идее не нужен драйвер нигде в page-классах, вы же selenide используете, а у него драйвер глобальный

2023-03-02 13:46 UTC, voropa commented on src/test/java/pages/ConfigurationsPage.java
> +    @Override
Смотрю, что во многих страницах у вас метод  public boolean isPageOpened() {
        return false;
    }
Всегда возвращает false и ничего не проверяет. В таком случае удалите его вообще из BasePage.
Либо, если все же хотите спользовать loadablePage pattern, то реализуйте этот метод во всех классах-наследнках, чтобы н действительно что-то проверял

2023-03-02 13:46 UTC, voropa commented on src/test/java/pages/HomePage.java
> +    private final static By PROJECTS_LINK = By.xpath("//a[@class='HC5SEf' and text()='Projects']");
Очень ненадежные эти классы по типу HC5SEf' в локаторах, лучше уже просто по  тексту искать

2023-03-02 13:46 UTC, voropa commented on src/test/java/pages/NewProjectPage.java
> +    private final static By PROJECT_NAME_TEXT = By.cssSelector(".sqabXr");
ТО же самое сс локатороми тут

2023-03-02 13:46 UTC, voropa commented on src/test/java/pages/RepositoryPage.java
> +    private final static By SUITE_NAME_LABEL = By.cssSelector(".DvbSwG");
И тут

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/ApiTests.java
> +    private final String expectedJson = "{\"status\":true,\"result\":{\"total\":3,\"filtered\":3,\"count\":3,\"entities\":[{\"title\":\"Demo Project\",\"code\":\"DEMO\",\"counts\":{\"cases\":10,\"sui
консстанты в java именуются в UPPER_CASE

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +protected final static String USERNAME = "tinkerbox@yandex.by";
username и pasword поместите в config.properties и вычитывайте их тут с помощью PrepertiesReader

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        Configuration.baseUrl = "https://app.qase.io";
url тоже помесстите в config.poperties

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        driver.navigate().refresh();
А зачем делать refresh() перед тем, как закрыть драйвер?

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/SuiteTests.java
> +        open("/login");
в тестах не должно быть driver- методов
open('login') стоит поместить в какой-то метод openLoginPage() внутри page-класса и вызывать его тут

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +        open("/projects");
То же самое

2023-03-02 13:46 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +        open("/projects");
Сделайте просто в ваших page классах методы open(), которые внутри себя будут вызывать selenide.open('...'
И тогда в тестах вы будете писать след. код:
loginPage.open()
или
projectsPage.open()

2023-03-02 18:37 UTC, EvgeniyAbramovich commented on src/test/java/pages/ConfigurationsPage.java
> +    @Override
Если я удаляю driver и isPageOpened из BasePage, то BasePage будет простой пустой?

2023-03-02 19:08 UTC, voropa commented on src/test/java/pages/ConfigurationsPage.java
> +    @Override
Ну фактически они же вам там не нужны. Да, будет пустой. Но в дальнейшем туда можно добавить какие-то общие методы и переменные, которые потом переиспользтся во всех остальных классах. Например, в basepage добавляют обычно ожидания всякие

2023-03-05 19:41 UTC, voropa requested changes

2023-03-05 19:41 UTC, voropa commented on src/test/java/elements/EditDetail.java
> +public class EditDetail extends BaseElement{
Что-то у вас тут странное. класс-декоратор должен описывать один элемент с одним локатором, а у вас тут 4 разных элемента внутри одного класса.

2023-03-05 19:41 UTC, voropa commented on src/test/java/tests/DefectTests.java
> +        newDefectModal.fillformDefects(defects).clickCreateDefectButton();
А проверка в тесте где?

2023-03-05 19:43 UTC, EvgeniyAbramovich commented on src/test/java/tests/DefectTests.java
> +        newDefectModal.fillformDefects(defects).clickCreateDefectButton();
Это недописанный тест. Я его видимо случайно закоммитил за компанию со всеми остальными

2023-03-05 19:44 UTC, EvgeniyAbramovich commented on src/test/java/elements/EditDetail.java
> +public class EditDetail extends BaseElement{
Я думал сделать один класс на все детали по всем пэйджам

2023-03-05 19:47 UTC, EvgeniyAbramovich commented on src/test/java/tests/DefectTests.java
> +        newDefectModal.fillformDefects(defects).clickCreateDefectButton();
А там на каждый созданный элемент (тест-кейс, сьют и т.д.) могут быть разные локаторы

2023-03-05 19:47 UTC, EvgeniyAbramovich commented on src/test/java/elements/EditDetail.java
> +public class EditDetail extends BaseElement{
А там на каждый созданный элемент (тест-кейс, сьют и т.д.) могут быть разные локаторы

2023-03-05 20:12 UTC, voropa commented on src/test/java/elements/EditDetail.java
> +public class EditDetail extends BaseElement{
Не, так не получится унифцровать) 
Декораторы делают для оодного конкретного элемента, точнее набора одиноковых элементов с идентичным или очень похожиим локатормо и поведением. А у вас тут 4 разных элемента, вот для них у нужно значит 4 класса-декоратора

2023-03-07 19:20 UTC, voropa requested changes

2023-03-07 19:20 UTC, voropa commented on src/test/java/elements/BaseElement.java
> +        log.info("Scrolling to element ={}",element);
Низкоуровневые технические действия типа scroll, wait обычно логируют на уровне debug(), а info() используют для логированя пользовательских действий по  типу click() getText()

2023-03-07 19:20 UTC, voropa commented on src/test/java/elements/DataPlaceHolderDetail.java
> +        log.info("Get value from input");
А их какого инпута получаете value? У вас же тут есть label, который можно подставить в текст лога, чтобы лог был более информативным

2023-03-07 19:20 UTC, voropa commented on src/test/java/elements/DataPlaceholder.java
> +        log.info("Set value = {}", value);
Тут тоже в лог можно передать 2 значения: label и value, чтобы было видно в какой элемент какое значение сетаете

2023-03-07 19:20 UTC, voropa commented on src/test/java/elements/InputDetail.java
> +
Отформатируйте этот класс, очень много пустых строк

2023-03-07 19:20 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        Configuration.baseUrl = PropertyReader.getProperty("qase.api_base_url");
Тут вероятно должен быть не qase.api_base_url, а qase.base_url, потому что он разные для api и для web приложения

2023-03-07 19:20 UTC, voropa commented on src/test/java/tests/ApiTests.java
> +    private final String EXPECTED_JSON = "{\"status\":true,\"result\":{\"total\":6,\"filtered\":6,\"count\":6," +
В таком виде тесты не будут работать так как проекты - динамически создаются/удаляются и при добавлдении илии удалении одного из проектов, этот expectedJSON уже будет не актуален. То же самое с тестом на создание  удаление проекта, они пройжут у вас один раз, а на второй раз уже нет, потому что такой проект уже создан или удален.

2023-03-07 19:20 UTC, voropa commented on src/test/java/tests/TestListener.java
> +        System.out.println("Test " + result.getName() + " started at" + new Date().toString());
Замените тут везде system.out.println на logger.info()

2023-03-08 20:49 UTC, voropa requested changes

2023-03-08 20:49 UTC, voropa commented on src/test/java/elements/DataPlaceholder.java
> +        log.info("Set value = {}{}", value,label);
Нуу, в таком случае у вас в логе будет написано слитно непонятный текст. Отформтируйте, чтобы это было читабельное сообщение, напрмер:
log.info("Setting '{}' value = {}", label,value);

2023-03-08 20:49 UTC, voropa commented on src/test/java/elements/DataPlaceholder.java
> +        log.info("Set value = {}{}", value,label);
В остальных местах тоже  проыверьие

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ApiDefectTests.java
> +import adapters.DefectAdapter;
Лучше вынесите api тесты в отдельный пакет внутри пакета tests:
tests/api

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ApiDefectTests.java
> +    @Test(description = "Create Defect Test", groups = {"API"})
Очень ненадежные тесты, потому что в них захардкоданы PROJECT_CODE = "123" и DEFECT_ID = 17.
Что если запустить тесты на аккаунте, в котором нет проекта с такимм кодом и дефекта с тааким ID? Они не пройдут.
Так что правильным решением будет создавать новый проект  и новый дефект в прекондишинах для этих тестов

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ApiDefectTests.java
> +    @Test(description = "Create Defect Test", groups = {"API"})
создавать соотвественно через API тоже)

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ApiProjectTests.java
> +    public void getProjectByCodeTest() {
Тут то же самое, вам нужно в перкондиишинах создать проект, чтобы потом делать getProject

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ApiProjectTests.java
> +    ProjectAdapter projectAdapter = new ProjectAdapter();
Да, и если уже пишете API тесты на какой-то endpoint, то нужно покрыть все методы тестами, а не только GET

2023-03-08 20:49 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +             {"Demo Project", "DEMO"},
Очень плохой тест, потому что он опирается на существующиие данные в конкретно вашем аккаунте, на конкретный момент времени. А тесты не должны быть привязаны к окружению и выполняться в любых условиях, например на новом аккаунте, где нет вообще проектов

2023-03-10 10:22 UTC, voropa requested changes

2023-03-10 10:22 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +    public Object[][] createNewProjectTest(){
Поменяйте название этого data-povider метожа. это же не тест, а набор данных, а в названии фигуррует слово "Test"

2023-03-10 10:22 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +   @AfterTest(description = "Delete Created Project1")
Что-то вы тут тоже намудрили, 4 AfterTest метода, которые удаляют проекты, еще и с захардкодаными именами, точнее projecCode. Сделайте один after метод, который просто будет в цикле проходится по всем проектам из data-provider и удалять их

2023-03-10 10:22 UTC, voropa commented on src/test/java/tests/ProjectTests.java
> +   @AfterTest(description = "Delete Created Project1")
Да и по сути какой смысл делать тест на создание проекта data-driven? Тут не проверяются какие-то граничные значения или разные комбинации параметров, а всегда создаются одинаковые проекты, только с разными именам и кодами...

2023-03-10 10:22 UTC, voropa commented on src/test/java/tests/SharedStepsTests.java
> +        String projectName = TEST_PROJECT_NAME;
Зачем заводть еще одну переменную String projectName, когда у вас и так есть глобальная константа в этом классе TEST_PROJECT_NAME, можно же прямо ее использовать в меоде. В других тестах то же самое

2023-03-10 10:22 UTC, voropa commented on src/test/java/tests/SuiteTests.java
> +    @BeforeTest(description = "Create Test Project")
У вас в каждом Test классе в before/after методах выполняются одни и те же действия по созданю  удалению проекта. Получается, что дублируется код везде. Сделайте просто в BaseTest методы BeforeClass / AfterClass, в которых будет создаваться и удаляться проект перед/после каждого набора тестов в каждом классе

2023-03-12 11:48 UTC, voropa requested changes

2023-03-12 11:48 UTC, voropa commented on ApiTest.xml
> +    <test name="API Tests" parallel="tests" thread-count="2">
Какой смысл тут писать parallel="tests" thread-count="2", когда у вас и так один <test> внутри xml файла. Еслии хотите распараллелить тесты, то тогда  уже  по классам нужно их параллелить внутри <test>

2023-03-12 11:48 UTC, voropa commented on Jenkinsfile
> +     choice(choices: ['Chrome', 'Firefox'], description: 'Select a browser', name: 'BROWSER')
Зачем тут параметры BROWSER и HEADLESS. если вы их поото не используете в команде для запуск тестов
 bat "mvn -Dmaven.test.failure.ignore=true -DsuiteXmlFile=${params.SUITE_NAME} clean test"

2023-03-12 11:53 UTC, voropa commented on src/test/java/tests/ApiProjectTests.java
> +    ProjectAdapter projectAdapter = new ProjectAdapter();
Для дефектов так точно нужно больше тестов написать, там же вот какой список api методов
<img width="387" alt="image" src="https://user-images.githubusercontent.com/14195681/224542829-ce648c38-232b-41d3-aed2-9dca3e4e0023.png">

2023-03-12 18:26 UTC, voropa requested changes

2023-03-12 18:26 UTC, voropa commented on ApiTest.xml
> +    <test name="API Tests" parallel="tests" thread-count="2">
Проверьте остальные xml файлы, у вас там тоже parallel="tests" thread-count="2", там где оно не имеет смысла

2023-03-13 17:46 UTC, voropa requested changes

2023-03-13 17:46 UTC, voropa commented on src/test/resources/log4j2.yaml
> +Configuration:
Что то у вас не пишуться логи при запуске тестов ни в консоль, ни в файл. Перепроверьте log4j.yaml, может неправильная сконфиигурирован
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/14195681/224785089-b39afc8a-20cd-4b1a-a9ee-5a81e58bf517.png">

2023-03-13 17:50 UTC, voropa requested changes

2023-03-13 17:50 UTC, voropa commented on RegressionTest.xml
> +<?xml version="1.0" encoding="UTF-8"?>
При запуске regression suite, получаю вот такие результаты:
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/14195681/224785778-335dab71-2340-4441-89cd-f2fd67a7251a.png">

2023-03-13 18:03 UTC, EvgeniyAbramovich commented on RegressionTest.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Я только что запускал. У меня все проходит
![Screenshot_3](https://user-images.githubusercontent.com/115666237/224789507-54f8c9f8-542f-4325-90f0-6dda9bf844ef.jpg)

2023-03-13 18:32 UTC, voropa requested changes

2023-03-13 18:32 UTC, voropa commented on src/test/java/tests/api/ApiDefectTests.java
> +       Assert.assertEquals(expectedResponse, actualResponse);
Вы сравниваете String и DefectResponse в ассерте, очевидно, что он будет падать. Вам нужно десериализовать  actualResponse в обьект и потом сравнивать их

2023-03-13 18:32 UTC, voropa commented on src/test/java/tests/api/ApiProjectTests.java
> -    private final String EXPECTED_JSON = "{\"status\":true,\"result\":{\"title\":\"Test Project Projects API\",\"code\":\"123\"," +
Сделайте этот EXPECTED_JSON динамической строкой и подставляйте туда название и код  проекта из констант выше, чтобы не приходилось всегда  в нескольких местах менять эти праметры

2023-03-13 21:22 UTC, merged